baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Prateek Chhajed"
  keywords = "homepage, blog, science, prateek, chhajed, prateek chhajed, development, programming, product management"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

 #  Google analytics
 googleAnalytics = "UA-151396153-1"

[languages]
  [languages.en]
    title = "Prateek Chhajed"
    subtitle = ""
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Hello World"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [[params.social]]
      name = "twitter"
      url  = "https://twitter.com/prateekchhajed1"

    [[params.social]]
      name = "email"
      url  = "mailto:prateekchhajed.52@gmail.com"

    #[[params.social]]
    #  name = "github"
    #  url  = "https://github.com/prateek52"

    [[params.social]]
      name = "linkedin"
      url  = "https://www.linkedin.com/in/pratik-chhajed-b41159ab"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

#Disqus
[[menu.main.DisqusShortname]]
disqusShortname = "prateekchhajed"
